// <auto-generated />
using System;
using Job.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Job.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180820181819_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Job.Data.Models.Rubric", b =>
                {
                    b.Property<Guid>("RubricId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("RubricId");

                    b.ToTable("Rubrics");
                });

            modelBuilder.Entity("Job.Data.Models.Vacancy", b =>
                {
                    b.Property<Guid>("VacancyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Header");

                    b.Property<string>("PositionTitle");

                    b.Property<string>("Salary");

                    b.Property<string>("Url");

                    b.Property<Guid>("VersionId");

                    b.HasKey("VacancyId");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("Job.Data.Models.VersionInfo", b =>
                {
                    b.Property<Guid>("VersionInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int>("CountDownloded");

                    b.Property<int>("DataType");

                    b.Property<string>("ErrorMessage");

                    b.Property<bool>("IsDownloaded");

                    b.Property<bool>("IsRemoved");

                    b.Property<DateTime>("UpdateAt");

                    b.HasKey("VersionInfoId");

                    b.ToTable("VersionInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
